stages:
- name: Build--api server image
  steps:
  - publishImageConfig:
      dockerfilePath: ./app/Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}/api-test:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 10.20.0.67:5443
    env:
      PLUGIN_INSECURE: "true"
      PLUGIN_MTU: "1000"
- name: deploy--API server
  steps:
  - applyYamlConfig:
      path: ./k8s-yaml/apitest-deployment.yaml
  - applyYamlConfig:
      path: ./k8s-yaml/apitest-service.yaml
  - applyYamlConfig:
      path: ./k8s-yaml/apitest-ingress.yaml
- name: Test--API Server
  steps:
  - runScriptConfig:
      image: 10.20.0.67:5443/dockerhub/library/ubuntu:18.04
      shellScript: sleep 60
- name: Test-Newman
  steps:
  - runScriptConfig:
      image: 10.20.0.67:5443/dockerhub/iiiorg/newman-runner:latest
      shellScript: ln -s "$(pwd)" /usr/src/app/repo; cd /usr/src/app; node /usr/src/app/app.js
    env:
      git_branch: ${CICD_GIT_BRANCH}
      git_url: ${CICD_GIT_URL}
      test_origin: http://apitest-${CICD_PIPELINE_ID}-${CICD_EXECUTION_SEQUENCE}-svc:5000
      verbose: "true"
    envFrom:
    - sourceName: api-origin
      sourceKey: api-origin
      targetKey: api_origin
    - sourceName: api-origin
      sourceKey: username
      targetKey: username
    - sourceName: api-origin
      sourceKey: password
      targetKey: password
- name: Code Review--run Checkmarx test
  steps:
  - runScriptConfig:
      image: 10.20.0.67:5443/dockerhub/iiiorg/checkmarx-runner:latest
      shellScript: ln -s "$(pwd)" /usr/src/app/repo; cd /usr/src/app; ls; echo ${api_orign};node app.js;
    env:
      git_url: ${CICD_GIT_URL}
      git_branch: ${CICD_GIT_BRANCH}
      git_commit_id: ${CICD_GIT_COMMIT}
      verbose: true
    envFrom:
    - sourceName: api-origin
      sourceKey: api-origin
      targetKey: api_origin
    - sourceName: api-origin
      sourceKey: username
      targetKey: api_username
    - sourceName: api-origin
      sourceKey: password
      targetKey: api_password
    - sourceName: gitlab-token
      sourceKey: git-token
      targetKey: git_token
    - sourceName: jwt-token
      sourceKey: jwt-token
      targetKey: jwt_token
    - sourceName: checkmarx-secret
      sourceKey: username
      targetKey: username
    - sourceName: checkmarx-secret
      sourceKey: password
      targetKey: password
    - sourceName: checkmarx-secret
      sourceKey: check-interval
      targetKey: check_interval
    - sourceName: checkmarx-secret
      sourceKey: client-secret
      targetKey: client_secret
    - sourceName: checkmarx-secret
      sourceKey: cm-url
      targetKey: cm_url
notification: {}
