apiVersion: v1
kind: Service
metadata:
  name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-apitest-svc
  namespace: ${CICD_GIT_REPO_NAME}
  labels: 
    app: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-apitest
spec:
  type: NodePort
  selector:
    app: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-apitest
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 32080
