apiVersion: v1
kind: Service
metadata:
  name: ${CICD_GIT_REPO_NAME}-apitest-svc
  labels: 
    app: ${CICD_GIT_REPO_NAME}-apitest
spec:
  type: NodePort
  selector:
    app: ${CICD_GIT_REPO_NAME}-apitest
  ports:
    - protocol: TCP
      port: 5000
