apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: apitest-ing
spec:
#
  rules:
  - host: "apitest.${CICD_PIPELINE_ID}.${CICD_EXECUTION_SEQUENCE}.10.20.0.80.xip.io"
    http:
      paths:
      - backend:
          serviceName: apitest-${CICD_PIPELINE_ID}-svc
          servicePort: 5000
        path: "/"
        pathType: "ImplementationSpecific"
